### ISSUE TITLE
Rewrite Build System

### ISSUE THREAD

**Issue by lukeadams** [SuperV1234/SSVOpenHexagon#126]
### TODO
- [x] Use CMake exclusively
- [x] Use CPM instead of Git Submodules (isolation between deps and source code)
- [ ] Linux+OS X reproducible builds (#22)
- [ ] Detect deps needed for build, warn+fail when they aren't found (#77, [comment](https://github.com/SuperV1234/SSVOpenHexagon/issues/94#issuecomment-29098063), 
- [ ] Wiki pages for building (#10, #113), maybe even contributing? (well, make the markdown docs show up in the GH wiki for better navigation)

My reasoning with going full-on CMake is to homogenize the build code (less platform-specific code == better). I think the issues with CMake on Windows can be improved by expanding the documentation.

What do you think? I'm setting up CPM on my copy (not public yet) and then I'm going to tackle rewriting the build scripts if you give the OK.

I love this game, so it will be fun to finally contribute! ;)

**Comment by SuperV1234** [comment]
Hello Luke, your proposal sounds great and very well thought-out. 
The build system present in OH (and my other projects) is horrible and hard to use and maintain. 

Go ahead and feel free to contact me here or via email if you need help with anything.

**Comment by lukeadams** [comment]
Yay! I'm glad you like it. I will definitely contact you if i need anything.

**Comment by lukeadams** [comment]
Just a heads up, I'm going to switch from CPM to [Hunter](https://github.com/ruslo/hunter) (CPM seems abandoned, Hunter seems much more robust).

**Comment by lukeadams** [comment]
So I have a `cpm` branch on most of the dependency repos (mostly a boilerplate CMakeLists.txt to make CPM happy). Now I'm just linking them together (so it builds – which it doesn't do yet :cry:). 
What do you think? ([here](https://github.com/lukeadams/SSVOpenHexagon/blob/cpm-deps/CMakeLists.txt#L27-L31) is an example of SSVCmake being included)

**Comment by lukeadams** [comment]
Also [CMake seems to have nice CC support built in](https://cmake.org/Wiki/CMake_Cross_Compiling). We _might_ be able to create Windows binaries on a Linux machine (with Travis – automatic builds!) :sweat_smile:

**Comment by SuperV1234** [comment]
Looks great! I'm not familiar with CPM, but (correct me if I am wrong), it seems to automatically download and update the latest dependencies from GitHub.

Some questions:

* Why have you decided to go with CPM and not Hunter?

* How are recursive dependencies handled (tree of libraries that depend on each other)?

* Is it still possible to easily build the project by manually pulling the dependencies in a folder and specifying the path?

**Comment by lukeadams** [comment]
Yes, CPM basically 1.) downloads a dep (from Git or otherwise), and 2.) lets you pin it to a Git tag for versioning / a branch. 
It also takes care of header inclusion (e.g. SSVEntitySystem would export its header file(s), consumers would not have to care about where the header actually is just reference by module name)  
So to answer your questions:
- CPM is much simpler than Hunter (which doesn't pull from git) – That's pretty much why I chose CPM for now. I like the way Hunter has a plugin system (one looks for Lua), but we already have a bunch of Cmake plugins you wrote to do that so...
- CPM (and I assume Hunter) does a neat dep graph where they all depend on the _same_ one (like a bunch of SSVOH deps depend on vrm_pp), so CPM makes them all use the same one. it throws an error on circular (a<==>b both include eachother)
- Yes, it would be trivial to provide a shell script that pulls them together

But yeah i think once i get OH building I might move to Hunter. CPM doesn't seem to be maintained anymore, while hunter seems to be under active development

**Comment by lukeadams** [comment]
I have the deps linked together – now to make it compile
```
Root
  | SSVCMake - GIT - Tag: cpm - Unid: github_lukeadams_ssvcmake_cpm
  | SSVEntitySystem - GIT - Tag: cpm - Unid: github_lukeadams_ssventitysystem_cpm
    | SSVCMake (reused) - GIT - Tag: cpm - Unid: github_lukeadams_ssvcmake_cpm
    | SSVUtils - GIT - Tag: cpm - Unid: github_lukeadams_ssvutils_cpm
      | SSVCMake (reused) - GIT - Tag: cpm - Unid: github_lukeadams_ssvcmake_cpm
      | vrm_pp - GIT - Tag: cpm - Unid: github_lukeadams_vrm_pp_cpm
        | SSVCMake (reused) - GIT - Tag: cpm - Unid: github_lukeadams_ssvcmake_cpm
    | vrm_pp (reused) - GIT - Tag: cpm - Unid: github_lukeadams_vrm_pp_cpm
  | SSVLuaWrapper - GIT - Tag: cpm - Unid: github_lukeadams_ssvluawrapper_cpm
    | SSVCMake (reused) - GIT - Tag: cpm - Unid: github_lukeadams_ssvcmake_cpm
  | SSVMenuSystem - GIT - Tag: cpm - Unid: github_lukeadams_ssvmenusystem_cpm
    | SSVCMake (reused) - GIT - Tag: cpm - Unid: github_lukeadams_ssvcmake_cpm
  | SSVStart - GIT - Tag: cpm - Unid: github_lukeadams_ssvstart_cpm
    | SSVCMake (reused) - GIT - Tag: cpm - Unid: github_lukeadams_ssvcmake_cpm
    | SSVUtils (reused) - GIT - Tag: cpm - Unid: github_lukeadams_ssvutils_cpm
    | vrm_pp (reused) - GIT - Tag: cpm - Unid: github_lukeadams_vrm_pp_cpm
  | SSVUtils (reused) - GIT - Tag: cpm - Unid: github_lukeadams_ssvutils_cpm
  | vrm_pp (reused) - GIT - Tag: cpm - Unid: github_lukeadams_vrm_pp_cpm
```
^ That's the dep tree. Note the `(reused)` on many of the entries.

**Comment by lukeadams** [comment]
Just a heads up: g++ or non-stock Clang must be installed to build on OSX. Apparently g* links to Clang [which doesn't allow thread_local](https://stackoverflow.com/questions/28094794/why-does-apple-clang-disallow-c11-thread-local-when-official-clang-supports) (I can not for the life of you explain why Apple chose to do that...)

**Comment by lukeadams** [comment]
Appveyor is free for OSS projects: https://www.appveyor.com/pricing

**Comment by lukeadams** [comment]
```cmake
add_custom_target("fetch-assets"
	COMMAND echo "Fetching"
)
```
So you can call `make fetch-assets` pre-build, or just make fetching part of the build process

**Comment by lukeadams** [comment]
!!!
![screen shot 2016-03-12 at 23 35 38](https://cloud.githubusercontent.com/assets/3508077/13727123/4f9ed2aa-e8ab-11e5-921a-8302b80b8b94.png)
OSX is working

**Comment by lukeadams** [comment]
Need to test on Windows/Linux.
On OSX to build:
```bash
brew install sfml --with-openal-soft
brew install llvm37 libffi lua homebrew/dupes/zlib cmake
mkdir build-root; cd build-root

git clone -b cpm-deps https://github.com/lukeadams/SSVOpenHexagon
mkdir build; cd build

cmake ../SSVOpenHexagon/ -G "Unix Makefiles" -DCMAKE_CXX_COMPILER=/usr/local/Cellar/llvm37/3.7.1/bin/clang++-3.7
make -j4 #4 jobs. Change to number of cores in system.
make copy-assets
cd test
./SSVOpenHexagon
```
...and it launches!
Might have missed a dep. Still need to verify which ones I ended up using...

**Comment by SuperV1234** [comment]
Awesome job! Glad to see it finally running on OSX.  Looking forward to the completed build system - let me know if you need help or want me to run some tests.

**Comment by SuperV1234** [comment]
This could be interesting: [cget](https://github.com/pfultz2/cget)
